# Generated by Django 4.1 on 2022-08-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_orderdetail_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
    ]
